apiVersion: apps/v1
kind: Deployment
metadata:
  name: agri-api-gateway
  labels:
    app: agri-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agri-api-gateway
  template:
    metadata:
      labels:
        app: agri-api-gateway
    spec:
      containers:
      - name: agri-api-gateway
        image: agri-api-gateway:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_CLOUD_GATEWAY_ROUTES_0_URI
          value: "http://agri-auth-service:8081"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_1_URI
          value: "http://agri-product-service:8082"
        - name: SPRING_CLOUD_GATEWAY_ROUTES_2_URI
          value: "http://agri-order-service:8083"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: agri-api-gateway
spec:
  selector:
    app: agri-api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort