apiVersion: apps/v1
kind: Deployment
metadata:
  name: agri-api-gateway
  annotations:

        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
      labels:
    app: agri-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agri-api-gateway
  template:
    metadata:
      