apiVersion: apps/v1
kind: Deployment
metadata:
  name: agri-backend
  labels:
    app: agri-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agri-backend
  template:
    metadata:
      labels:
        app: agri-backend
      # ===== HASHICORP VAULT AGENT INJECTOR =====
      # C'est ici que l'approche DevSecOps de Vault prend effet
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "agri-backend-role"
        vault.hashicorp.com/agent-inject-secret-application.properties: "secret/data/agri/db"
        vault.hashicorp.com/agent-inject-template-application.properties: |
          {{- with secret "secret/data/agri/db" -}}
          spring.data.mongodb.uri=mongodb://{{ .Data.data.username }}:{{ .Data.data.password }}@agri-mongodb:27017/agricultural_marketplace
          server.port=8080
          {{- end }}
    spec:
      serviceAccountName: agri-backend-sa
      containers:
      - name: agri-backend
        image: agri-backend:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_CONFIG_ADDITIONAL_LOCATION
          value: "file:/vault/secrets/application.properties"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: agri-backend
spec:
  selector:
    app: agri-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
