apiVersion: apps/v1
kind: Deployment
metadata:
  name: agri-order-service
  annotations:

        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"
        prometheus.io/path: "/actuator/prometheus"
      labels:
    app: agri-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agri-order-service
  template:
    metadata:
      